### ISSUE TITLE
[Must Have] - Levels still accessible with "selectable: false"

### ISSUE THREAD

**Issue by AlphaPromethium** [SuperV1234/SSVOpenHexagon#236] opened 2020-07-21 17:51 UTC
![image](https://user-images.githubusercontent.com/25865659/88088977-dfaaed80-cbbd-11ea-91d4-508fcd84f44f.png)

_thonk_

Steps to reproduce:
1. Go to any level property's JSON and change `"selectable"` to `false`.
2. Launch the game.

**Expected:** The level can no longer be selected.
**Actual:** The level is still selectable.

A/C:
1. Fix this bug.

**Comment by Morxemplum** [comment] 2020-08-14 14:22
I know what the issue is. Fixing this now

**Comment by Morxemplum** [comment] 2021-04-03 07:26
Vee doesn't like the fix, even though the fix does exactly what 1.92 did to unselectable levels. However, I'm closing this issue because I'm moving this issue over to #333, where I will have this issue be solved by having the level option grayed out and unplayable instead of not loading the level at all (considering that's what Vee wants)

**Closed by Morxemplum** 2021-04-03 07:26 UTC
Labels: bug
